### ISSUE TITLE
Documentation external to schema

### ISSUE THREAD

**Issue by kmccurley** [ror-community/ror-schema#9]
It would be nice to have a link from the README.md back to the definitions of the fields in this schema. For example, aliases is a list of strings, and presumably these could be in any language. In the example of https://ror.org/05vghhr25 the labels are repeated under aliases. The example of https://ror.org/00hgy8d33 has labels but no aliases. https://ror.org/01wddqe20 has aliases but no labels. Other than the language specification on labels, what is the relationship between these two fields?

**Comment by amandafrench** [comment]
Ah, that's a good idea, if I'm understanding you correctly: editing the README.md in this repository to list (or link to) the field definitions at https://ror.readme.io/docs/ror-data-structure , correct? We can do that. 

To answer your specific question about `labels` and `aliases,` `labels` is used for common translations of the name of of the organization into other languages -- hence the language specification. `aliases` is used for alternate names for the the organization, usually (though not always) in the same language as the mostly commonly used name for the organization. 

Any single record could of course need updating, and we're happy to take requests for modifications, but in your examples: 

* https://ror.org/01wddqe20 has aliases but no labels probably because researchers and publishers usually refer to The Alfred Hospital in English but sometimes just nickname it The Alfred;  

* https://ror.org/00hgy8d33 has labels but no aliases probably because researchers and publishers often give the name of the Defence Research and Development Canada in French (obviously a very common practice in Canada) but have no common nicknames or alternate names for it (other than acronyms, which are stored in `acronyms`); and 

* https://ror.org/05vghhr25 has the same two values in labels and aliases for no good reason and should probably be corrected so that the values are only in `labels`, since they are just translations of the English name "University of Turku" into Finnish and Swedish. I'll file an issue. 

Hope that helps. If you want a longread on the topic you might take a look at a recent blog post we did on [how ROR handles name metadata](https://ror.org/blog/2022-08-31-name-metadata-in-ror/).

**Comment by amandafrench** [comment]
Updated the README.md -- thanks for the suggestion, @kmccurley : https://github.com/ror-community/ror-schema/blob/master/README.md
